### ISSUE TITLE
Config via JSON object

### ISSUE THREAD

**Issue by indolering** [lancedikson/bowser#127]
It would be nice if you could just load a static JSON config object:

```
bowser.test({
  whitelist: {
    safari: "=>8",
    chrome: "42+",
    firefox: "40-43",
    ie: "<11"
  },
  blacklist: { ... }
})
```

Supporting Selenium capabilities would be nice, this would essentially require generating a whitelist, mapping key/value pairs, and implicitly converting versions to version ranges.  List of keys can be found [here](https://selenium.googlecode.com/svn/trunk/docs/api/py/_modules/selenium/webdriver/common/desired_capabilities.html). [SuaceLabs](https://wiki.saucelabs.com/display/DOCS/Platform+Configurator#/) and [BrowserStack](https://www.browserstack.com/automate/capabilities) ([see also](https://www.browserstack.com/automate/node)) utilize custom extensions, but it would be trivial to support them.

**Comment by indolering** [comment]
We should probably have an implicit whitelist.

**Comment by lancedikson** [comment]
@indolering, hey, Zach! Yeah, it looks good. But let me see a case, when you need a blacklist, please. I didn't catch this point. I mean, what result will you get in all cases of catches: 

- browser included to the `whitelist`
- browser included to the `blacklist`
- browser not included to any list
- browser included to both of them

**Comment by joaocc** [comment]
Hi,
We have a similar need for a wrapper around some Unity3D-based games.
As of 2016-09, on a PC, WebPlayer-based games are supported on IE, Firefox (not for much longer) and Chrome < 42. For Chrome and Edge, you must use WebGL. 
However, for some games, some versions of browsers are too slow so, in our case, they would be blacklisted.
Since we have to generate both builds (WebPlayer and WebGL), being able to pinpoint the correct browser and version is critical for a decent user experience.
Hope this helps understanding the need

**Comment by lancedikson** [comment]
It will be able to do with the 2.0 version soon. Move the discussion to #175.
