### ISSUE TITLE
Can the library also return the OS version.

### ISSUE THREAD

**Issue by karthikbr82** [lancedikson/bowser#176]
It would be great if bowser could detect the OS version as well especially for Mac and Windows. Right now it only detects the OS name.

**Comment by lancedikson** [comment]
Hey @karthikbr82! Look what we have for you :) The quote from the docs:

> `osversion` may also be set:
> `osversion` - for Android, iOS, Windows Phone, WebOS, Bada, and Tizen. If included in UA string.

Sometimes it's possible to get Mac OS version from the UserAgent string, but unfortunately not all the time. But, I think it's good point to improve, so will mark it like "help needed" since I don't have enough time to solve all the problems here at the moment 😞 

Feel free to send a PR. This is doable the same way like we do it for Android and iOS.

**Comment by rkurbatov** [comment]
@lancedikson here is PR for adding Windows/MacOS version support (if it can be read from UA): https://github.com/lancedikson/bowser/pull/178

**Comment by lancedikson** [comment]
Thanks, @rkurbatov! I'll have a look on it today 👍
