### ISSUE TITLE
Google Search App detection

### ISSUE THREAD

**Issue by ArTiSTiX** [lancedikson/bowser#196]
I recently discovered an official Google Search App which is a web browser different than Safari or Google Chrome.
This browser has some strange webview behaviour (i noticed some bugs with viewport dimensions).
I would like to detect it with bowser, could it be considered as a browser flag (i suggest 'gsa') ?
It's only reported as a webkit.
It would be easy to regex match /GSA/.

`window.navigator.userAgent` of the browser is: `Mozilla/5.0 (iPhone; CPU iPhone OS 10_3_3 like Mac OS X) AppleWebKit/602.1.50 (KHTML, like Gecko) GSA/34.1.167176684 Mobile/14G60 Safari/602.1`

**Comment by lancedikson** [comment]
@ArTiSTiX, have you found any official or public information somewhere else about those issues with viewport dimensions? I have to have a more accurate look at the problem you have.

**Comment by lancedikson** [comment]
Also, I have to make sure that GSA for sure uses any specific webview to provide any solution for it.

**Comment by Sembiance** [comment]
Ugh. The Google Search App is the bane of my existence. It puts this "toolbar" over the bottom of the page. However it is overlayed it on top of the page (instead of resizing the page). Thus it covers up the content on the bottom of the page. This makes my web game pretty hard to use since I don't have a scroll bar on my web game.

So I'd also love to be able to more accurately detect this browser in order to work around this toolbar because so far I haven't found any way to opt out of the toolbar using meta tags or something.

Here is the user agent I got:
```Mozilla/5.0 (iPad; CPU OS 11_0_3 like Mac OS X) AppleWebKit/604.1.34 (KHTML, like Gecko) GSA/38.0.172903409 Mobile/15A432 Safari/604.1```

**Comment by BTBDigital** [comment]
I would second this. Not been able to find much online about it either. But it's definitely [a distinct browser](https://www.google.co.uk/search?q=gsa+browser). The way it handles the viewport is really horrible...

**Comment by Sembiance** [comment]
The way I handle this is first I detect GSA via userAgent and also ensure it's iOS via bowser, then I modify the body height.

```
if(bowser.ios===true && window.navigator.userAgent.indexOf(" GSA/")!==-1)
  document.body.style.height = "calc(100% - 150px)";
```

The reason I check for ios===true is because the Google Search App on Android doesn't have the annoying bar overlay (although I did not check to see if it has the same GSA user agent part or not.

**Comment by darkowic** [comment]
Here is a result from whatismybrowser - whatismybrowser.com/w/WKFAR69

**Comment by lancedikson** [comment]
If I understood correctly, it's some sort of app made by Google, right? So, it could be detected as `GSA` by bowser as well then, I guess.

**Comment by Sembiance** [comment]
Yes, if you go to the iTunes app store, it's the "Google" app, from Google.

**Comment by lancedikson** [comment]
Ok, so yeah, we can just add its support like a new browser. Is anybody here feels like coming up with a PR for this one? :)

**Comment by Sembiance** [comment]
By the way, the more recent versions of this browser are better behaved as the 'toolbar' is no longer an overlay on the webpage but is properly outside of the viewport. So I actually no longer need to detect for GSA anymore.

**Comment by paulrosen** [comment]
Yes, it is being reported as "safari" for my users. Unfortunately, iOS doesn't allow it to use getUserMedia, so I need to weed it out.

My first thought is to look for the UA with all the version numbers wildcarded. Does anyone know if that will produce false positives?
