### ISSUE TITLE
Firefox on iOS - Request Desktop Site

### ISSUE THREAD

**Issue by beloi** [lancedikson/bowser#209]
Hello,

The browser version is not set when I'm switching from mobile site (default) to desktop site.

`window.navigator.userAgent` of the browser is:

> Mozilla/5.0 (iPad; CPU OS 9_3_5 like Mac OS X) AppleWebKit/601.1.46 (KHTML, like Gecko) FxiOS/8.3b5826 Mobile/13G36 Safari/601.1.46

`window.navigator.userAgent` when requesting desktop site is:

> Mozilla/5.0 (Macintosh; Intel Mac OS X 10_11_1) AppleWebKit/601.1.46 (KHTML, like Gecko) Safari/601.1.46

Latest Firefox on an iPad 3 running iOS 9.3.5 (UA examples above) and iPhone 5 running iOS 10.3.3.

**Comment by lancedikson** [comment]
Hi, @beloi! It seems to be a problem since the desktop's UA string doesn't say anything about the version. I guess it's because of the browser itself makes just an emulation of a desktop, which is, well, not a real desktop browser. That could be a reason for not having any version mark in UA string.

Maybe there is a way to get the real UA string of the browser even though it's run on "desktop mode". But this is mostly about a trick that could help you to identify the browser. Try to find it. There is nothing to do with this in bowser. Sorry.

**Comment by beloi** [comment]
Thank you, @lancedikson.
