### ISSUE TITLE
npm latest pointing to 2.0.3-beta 

### ISSUE THREAD

**Issue by ZhangYiJiang** [lancedikson/bowser#262]
Just letting you know that latest on npm is currently pointing to the beta release (2.0.3) of the library. This means that anyone installing the module via `npm install` or `npm upgrade` will automatically get this version instead of the "stable" version 1.9.4. 

Usually the `next` tag is pointed at the beta or head of branch, not `latest`. If this intended feel free to close this issue.

**Comment by lancedikson** [comment]
Hi, @ZhangYiJiang. Thanks for bringing this topic up. I've never used or changed the npm tags for the project. I suppose, we have to fix this, but I'm afraid to break anything for those, who may already rely on the beta version using the `latest` tag. So, I'd rather release stable 2.0.0 first, and then change the way of using these tags. I suppose it will happen quite soon since the beta version seems to be ready for production.

**Comment by lancedikson** [comment]
I'll close this issue since the latest version now is the stable 2.0.0. But, next time we'll release beta versions with the `beta` tag instead of latest. Thanks for the heads up 👍
