### ISSUE TITLE
uc browser is not detect using .check on stritc mode

### ISSUE THREAD

**Issue by henriquecustodia** [lancedikson/bowser#268]
Template to report about browser detection issue

`window.navigator.userAgent` of the browser is: 
![image](https://user-images.githubusercontent.com/5140430/48084233-503d8b00-e1de-11e8-8628-179358aa165d.png)

I'm trying check if user browser/OS is supported in my app. IE, Oldest android, chrome, so on...works fine, but UC Browser is never detected.

```js
bowser.check({
            android: '4.3',
            ios: '9.3',
            safari: '9',
            chrome: '29',
            firefox: '28',
            msie: '11',
            msedge: '12',
            opera: '17',
}, true, userAgent);
```

Bowser version: v1.9.3

**Comment by lancedikson** [comment]
Hi, @henriquecustodia. What kind of result do you get running this statement on the browser, you've provided? It should be `false`, as I understood

**Comment by henriquecustodia** [comment]
Hi @lancedikson, I believe the result is `true` because my code doesn't any action (the action is show a message). 

The code is: 
```js
 function isSupportedBrowser() {
        return bowser.check({
            android: '4.3',
            ios: '9.3',
            safari: '9',
            chrome: '29',
            firefox: '28',
            msie: '11',
            msedge: '12',
            opera: '17',
        }, true, window.navigator.userAgent);
    }

 if (!isSupportedBrowser()) {
        if (bowser.mobile) {
            createMobileImage();
        } else {
            createDesktopImage();
        }
    }
```
 
The `bowser.check` function is running on strict mode, so based on docs any not specified browser/OS would should return `false`.

>   When strict mode is enabled then any not specified browser family in minVersions will cause check to return false

**Comment by henriquecustodia** [comment]
@lancedikson I think it's a bug pending in my project, did you figure out what's the problem?

**Comment by lancedikson** [comment]
Yes, I checked this issue out and it turned out that there was a bug specific for 1.x version. In a nutshell, there took place an overlapping of the `Android browser` and `android platforms`, since both were defined as the `android` flag. But, it should be fine with 2.0 and its `.satisfies` method: https://github.com/lancedikson/bowser/blob/master/test/unit/parser.js#L89. I recommend using the new version and I don't think, that some day we will come up with the overlapping fix in 1.x branch as it's unofficially deprecated in favour of 2.0.

**Comment by lancedikson** [comment]
I hope it helped you. Closing for now.
