### ISSUE TITLE
Chromebook not reporting "getPlatformType()"

### ISSUE THREAD

**Issue by paulrosen** [lancedikson/bowser#319]
`window.navigator.userAgent` of the browser is: `Mozilla/5.0 (X11; CrOS x86_64 11021.81.0) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/70.0.3538.110 Safari/537.36`
 And it's detected like:
```
const bowser = bowserPackage.getParser(window.navigator.userAgent);
const parsed = JSON.stringify(bowser.parsedResult);
const platform = bowser.getPlatformType().replace(/[^a-zA-Z0-9]+/g,'-');
console.log(parsed); // "Linux x86_64"
console.log(platform); // ""
```
This is on a Chromebook. I'm trying to determine if this is mobile or desktop. In all of the other user's systems we've used this on platform is either "mobile" or "desktop".

**Comment by lancedikson** [comment]
@paulrosen, sorry for a late response. Did you manage to fix the problem?
Now if I use the UA string you gave in the issue, bowser returns this `parsedResult`:
```
{
  browser: { name: 'Chrome', version: '70.0.3538.110' },
  os: { name: 'Chrome OS' },
  platform: {},
  engine: { name: 'Blink' }
}
```
So, the point here is that it cannot determine the platform — the UA doesn't say a thing about it, unfortunately.

**Comment by paulrosen** [comment]
I just have a workaround for the moment. I'm doing the following:
```
if (!platform && window.navigator.platform === "Linux x86_64") {
  platform = (window.innerWidth > 600) ? 'desktop' : 'mobile'; // Just a guess.
}
```
Definitely not the best - but it's working ok for us.

**Comment by hwhelchel** [comment]
Based on this issue I went with this function

```js
isDesktop = () => {
  const browser = Bowser.getParser(window.navigator.userAgent);
  if(browser.getPlatformType() !== '') {
    return browser.getPlatformType() === 'desktop';
  } else {
    return window.innerWidth > 600;
  }
}
```

**Comment by lancedikson** [comment]
Well, for now `bowser` is considered as a UA parsing tool and can be run in Node as well, so we can't fix the issue systematically including this workaround with `window.innerWidth` into the library. If the UA doesn't say a thing about the platform, we leave this on developers' shoulders to decide what else they can use to get the needed information.

As for me, the solution suggested by @hwhelchel looks good, but maybe I'd use 
`browser.isPlatform('desktop')` instead of `browser.getPlatformType() === 'desktop'`.

So, closing for now :)
