### ISSUE TITLE
Incompatibility with Internet Explorer 11 : SCRIPT438: Object doesn't support property or method 'find'

### ISSUE THREAD

**Issue by slolo2000** [lancedikson/bowser#359]
Hello,

It seems that bowser v2.5.3 and even v2.6.1 is not compatible with Internet Explorer 11.

You can simply reproduce the problem with the following line:
var browser = bowser.getParser(window.navigator.userAgent);

I have the following error message int he console:
SCRIPT438: Object doesn't support property or method 'find'
es5.js (1,6915)

It works correctly with Edge, Chrome, Firefox.

Are you able to reproduce it?

Thanks in advance and have a nice day.

**Comment by CRiva** [comment]
Any update on this issue? I have just ran into it as well.

**Comment by slolo2000** [comment]
@lancedikson 
You have just released a new version but the problem still exists.
Do you need help to find a solution?

**Comment by raphael22** [comment]
@lancedikson 
Any update would be grateful ! ^^
Bowser should really not be based on any polyfill and be compliant with older browsers.
Or provide an ES6 and ES5 version.
But to quickfix this I suggest going oldschool and for a loop instead of a find.

**Comment by raphael22** [comment]
Thanks for quick response.
Take care bro.

**Comment by lancedikson** [comment]
Thanks :) Btw, I have to ask first: did you try using the polyfilled version of bowser? It's mentioned in Readme: `require('bowser/bundled')`. It must fix the problem right away :)

**Comment by raphael22** [comment]
Oh yeah didn't see that part.
I guess I will go with a custom webpack to build a es5 version of my lib with the "nomodule" script tag hack.
Is there a lot of ES6 features except "find" in your es5 version ?
Could be nice to be IE11 compliant without polyfills. :)

**Comment by lancedikson** [comment]
Yeah, I got your point. I'll try to setup babel properly so that it would not include all the polyfills for certain browsers, but only those, which are needed for bowser since now it seems to include lots of other polyfills.

**Comment by lancedikson** [comment]
Well, we have two problems here: 
1. On the one hand, the `es5.js` file is called wrong now and it's not ES5-compatible due to several reasons, one of them is this `Array.prototype.find`.
2. I could fix that and make the `es5.js` file to be ES5-compatible, but it would require to include polyfills and made the file grow up to 46Kb. 

Now, that 23Kb version of the file is something in the middle between ES5 and ES6, but it weights not that much, but still requires some polyfills from an end user if they want it to work in older browsers.

I'll try to dig deeper in finding a proper solution so that it won't blow up the file size and would still support older browsers, but for now I recommend simply add a polyfill for this `Array.prototype.find` from mdn as a hotfix and I'll be back with a better solution a bit later: https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Array/find#Polyfill.

**Comment by raphael22** [comment]
If you really need to rely on "find" maybe you could go with the module/nomodule hack:
```html
<script type="module" src="bowser.js"></script>
<script nomodule defer src="bowser-es5.js"></script>
```

**Comment by oliverfoster** [comment]
For IE11 it seems to be:
* `Object.assign` (`bowser.parse`) 
* `Array.prototype.find` (`Parser`)

**Comment by kankaristo** [comment]
Any news on this issue?

We had to roll back to an older version of Bowser because of this.

Our app doesn't even support IE, but we use Bowser to detect unsupported browsers, so we can show the users which browsers they should use instead of their current one (for example, on iOS only Safari has WebRTC support, which our app needs).

A browser detection library like Bowser should ideally support all possible browsers (with reasonable limits), even if the apps that use Bowser don't support those browsers.
